# Generated by Django 5.0.6 on 2024-05-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
