# Generated by Django 5.0.6 on 2024-05-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_user_is_client_user_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
