# Generated by Django 5.0.6 on 2024-05-13 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_order_products_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
