# Generated by Django 5.0.6 on 2024-05-13 09:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 6, 12, 9, 45, 25, 886360, tzinfo=datetime.timezone.utc))),
                ('max_usage_count', models.PositiveIntegerField(default=1)),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
