# Generated by Django 5.0.6 on 2024-05-13 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_discountcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 10, 27, 53, 996230, tzinfo=datetime.timezone.utc)),
        ),
    ]
