# Generated by Django 5.0.6 on 2024-05-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_newsarticle_alter_discountcoupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to='catalog/static/logos'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 16, 46, 50, 686822, tzinfo=datetime.timezone.utc)),
        ),
    ]
