# Generated by Django 5.0.6 on 2024-05-16 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_discountcoupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 18, 25, 45, 366531, tzinfo=datetime.timezone.utc)),
        ),
    ]
